
{{ config(materialized='table') }}

select 1 AS ID, 'BU1' AS BUSINESSUNIT, 'Marine Cargo' AS DESCRIPTION, CURRENT_TIMESTAMP as CREATED_AT
UNION
select 2 AS ID , 'BU2' AS BUSINESSUNIT, 'Marine Energy' as DESCRIPTION,CURRENT_TIMESTAMP as CREATED_AT
UNION
SELECT 3 AS ID, 'BU3' AS BUSINESSUNIT,'Agriculture Treaty' AS DESCRIPTION,CURRENT_TIMESTAMP as CREATED_AT
UNION
SELECT 4 AS ID,'BU4' AS BUSINESSUNIT, 'Ports and Terminal' as Description,CURRENT_TIMESTAMP as CREATED_AT
UNION
SELECT 5 AS ID,'BU5' AS BUSINESSUNIT, 'Aviation Ports' as Description,CURRENT_TIMESTAMP as CREATED_AT
UNION
SELECT 6 AS ID,'BU6' AS BUSINESSUNIT, 'Railway Corporation' as Description,CURRENT_TIMESTAMP as CREATED_AT
UNION
SELECT 7 AS ID,'BU7' AS BUSINESSUNIT, 'Cargo And Spiece' as Description,CURRENT_TIMESTAMP as CREATED_AT