{{ config(materialized='table') }}

select 
bu.ID AS BUSINESS_ID,
ER.ID AS CURRENCY_ID,
AC.ID AS ACCOUNT_ID,
--bu.ACCOUNTTYPE, 
--bu.YEAROFACCOUNT, 
ST.ACCOUNTINGPERIOD,
ST.TRANSACTIONDATE,
CASE WHEN ST.TRANSACTIONTYPE ='Credit' then 'C' 
     when ST.TRANSACTIONTYPE ='Debit' then 'D' ELSE 'NA' END AS TRANSACTIONTYPE,
--bu.ORIGINALCURRENCY,
--bu.SETTLEMENTCURRENCY,
 st.ORIGTRANSACTIONAMOUNT,
st.SETTTRANSACTIONAMOUNT,
st.ORIGTAXAMOUNT, 
st.SETTTAXAMOUNT,
current_timestamp as created_at
FROM
{{ ref('src_business_units') }} ST
LEFT JOIN CHAUCER_POC.CHAUCER_GOLD.DIM_BUSINESS_UNITS BU
       ON ST.BUSINESSUNIT =BU.BUSINESSUNIT
       LEFT JOIN CHAUCER_POC.CHAUCER_GOLD.DIM_EXCHANGE_RATES ER
       ON ST.ORIGINALCURRENCY =ER.CURRENCY
       AND ER.SETTLEMENTCURRENCY = ST.SETTLEMENTCURRENCY
                LEFT JOIN CHAUCER_POC.CHAUCER_GOLD.DIM_ACCOUNTS AC
                ON AC.ACCOUNTTYPE =ST.ACCOUNTTYPE
                AND AC.ACCOUNTNO =ST.ACCOUNTNO
                AND AC.YEAROFACCOUNT=ST.YEAROFACCOUNT
               /* AND ST.TRANSACTIONDATE = ( SELECT MAX(TRANSACTIONDATE)
                                            FROM {{ ref('src_business_units') }} ST1
                                            WHERE ST.BUSINESSUNIT = ST1.BUSINESSUNIT
                                            AND ST.ACCOUNTNO =ST1.ACCOUNTNO ) ORDER BY 1*/
                                            